name: CI Build

on:
  push:
    paths:
    - /AzDoExtensionNews/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: dotnet restore /AzDoExtensionNews/AzDoExtensionNews.sln
    - run: dotnet build /AzDoExtensionNews/AzDoExtensionNews.sln -c Release
    - run: dotnet test /AzDoExtensionNews/AzDoExtensionNews.sln
    - run: dotnet publish /AzDoExtensionNews/AzDoExtensionNews.sln -c Release