name: CI Build

on:
  push:
    paths:
    - AzDoExtensionNews/*
    - .github/workflows/ci-build.yml
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln
    - run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release
    - run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln
    - run: dotnet publish AzDoExtensionNews/AzDoExtensionNews.sln -c Release
