name: CI Build

on:
  push:
    paths:
    - AzDoExtensionNews/**
    - .github/workflows/ci-build.yml
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup the environment:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    # build it:
    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release

    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    # publish the AzDo news:
    - name: Publish AzDo News
      run: dotnet publish AzDoExtensionNews/AzDoExtensionNews/AzDoExtensionNews.csproj -c Release -o publish/AzDo/

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@v2
      with:
        path: publish/AzDo
        name: AzDoNews

    # also publish GitHub news:
    - name: Publish GitHub News
      run: dotnet publish AzDoExtensionNews/GitHubActionsNews/GitHubActionsNews.csproj -c Release -o publish/GitHub/

    - name: Publish GitHub Artifact
      uses: actions/upload-artifact@v2
      with:
        path: publish/GitHub
        name: GitHubNews