name: Tweet Scehduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "* */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release

    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@v2
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ArtifactName }}

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      # - name: App Settings Variable Substitution
      #   uses: microsoft/variable-substitution@v1
      #   with:
      #     files: '${{steps.download.outputs.download-path}}/drop/GH/appsettings.json/appsettings.json'
      #   env:
      #     TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
      #     TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
      #     TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
      #     TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
      #     BlobStorageConnectionString: ${{ secrets.BlobStorageConnectionString }}